steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - "-c"
      - |
        gsutil cp gs://be-the-hero-275300.appspot.com/secrets/frontend/.env .env
        gsutil cp gs://be-the-hero-275300.appspot.com/secrets/frontend/google-service-account.json google-service-account.json
    timeout: "600s"
  - name: node:${_NODE_VERSION}
    entrypoint: bash
    args:
      - "-c"
      - |
        yarn install --production
        yarn run react-scripts build
    env:
      - "NODE_ENV=${_NODE_ENV}"
    timeout: "600s"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "client.yaml", "--no-promote"]
    timeout: "600s"
substitutions:
  _NODE_VERSION: "12"
  _NODE_ENV: "production"
