steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - "-c"
      - |
        gsutil cp gs://be-the-hero-275300.appspot.com/secrets/backend/.env .env
        gsutil cp gs://be-the-hero-275300.appspot.com/secrets/database/ssl/client/root.crt ./ssl_cert/postgres/root.crt
        gsutil cp gs://be-the-hero-275300.appspot.com/secrets/database/ssl/client/client.crt ./ssl_cert/postgres/client.crt
        gsutil cp gs://be-the-hero-275300.appspot.com/secrets/database/ssl/client/client.key ./ssl_cert/postgres/client.key
    timeout: "600s"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "api.yaml", "--no-promote"]
    timeout: "600s"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "dispatch.yaml"]
    timeout: "600s"
